# ─────────────────────────────────────────────
# FOTW Mesh Federation – Project Meridian
# Docker Compose configuration
# ChainFeed nodes connect to native Redis
# ─────────────────────────────────────────────

services:
  chainfeed_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: chainfeed-node
    container_name: chainfeed_node
    environment:
      NODE_ID: ${NODE_ID}
      ENTITY_NAME: ${ENTITY_NAME}
      DIVISION: ${DIVISION}
      MESH_ROLE: ${MESH_ROLE}
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      MODE: ${MODE}
      GROUP: ${GROUP}
    volumes:
      - .:/app
    command: >
      sh -c "python -m core.startup.startup_sequence --node ${NODE_ID}"

networks:
  default:
    name: chainfeed_default