variant: FatTail
default_dte: 0
max_dte: 5

symbols:
  - symbol: SPX
    alias: S&P 500 Index
    dtes: [0, 1, 2, 3, 4, 5]
  - symbol: NDX
    alias: Nasdaq 100 Index
    dtes: [0, 1, 2, 3, 4, 5]
  - symbol: ES
    alias: E-mini S&P
    dtes: [0, 1, 2, 3, 4, 5]

groups:
  spx_complex:
    description: "S&P 500 Index feed complex (SPX only)"
    symbols: ["SPX"]
    feeds: ["full", "diff"]

  ndx_complex:
    description: "Nasdaq 100 Index feed complex (NDX only)"
    symbols: ["NDX"]
    feeds: ["full", "diff"]

  index_complex:
    description: "Combined index complex (SPX + NDX)"
    symbols: ["SPX", "NDX"]
    feeds: ["full", "diff"]

heartbeat:
  enabled: true
  interval_sec: 5